name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We'd love to hear your ideas for improving CodGuard for WooCommerce!

  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: What would you like to see added?
      placeholder: "Add ability to customize the rejection message shown to customers..."
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
      description: What problem does this solve for you?
      placeholder: "I want to show different messages in different languages..."
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Current Workaround
      description: How are you handling this now (if at all)?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Critical - blocking my business
        - High - would be very helpful
        - Medium - nice to have
        - Low - just an idea
    validations:
      required: true
